### Login a company
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "tec234",
  "password": "-w8*2g^gljwr"
}

> {%
  client.global.set("tecToken", response.body.token);
%}

### Validate a company
POST http://localhost:8080/companies/3/validate
Content-Type: application/json

{
  "companyId": 3,
  "name": "Blue Horizon Ventures",
  "companyNumber": "45432345678",
  "legalForm": "SARL",
  "address": "L'adresse de la company",
  "naceCode": "1234",
  "templates": ["ALL"],
  "scores": [],
  "isValidated": false,
  "contactEmail": "ouarrad.dania@gmail.com"
}
