### Read all forms in progress
GET http://localhost:8080/forms/1/progress


### Create a form
POST http://localhost:8080/forms/4

### Get all forms
GET http://localhost:8080/forms

### Get a form
GET http://localhost:8080/forms/6

### Save the form
POST http://localhost:8080/forms/6/saveAnswers
Content-Type: application/json

[
  {
    "questionId": 18,
    "response": "Oui"
  },
  {
    "questionId": 19,
    "response": "test"
  },
  {
    "questionId": 20,
    "response": "Nous avons installé des systèmes de détection des fuites."
  },
  {
    "questionId": 26,
    "response": "Oui"
  },
  {
    "questionId": 27,
    "response": "test"
  },
  {
    "questionId": 28,
    "response": "test"
  },
  {
    "questionId": 29,
    "response": "Autre : veuillez expliquer dans les commentaires"
  },
  {
    "questionId": 1,
    "response": "Oui"
  },
  {
    "questionId": 2,
    "response": "Je ne sais pas"
  },
  {
    "questionId": 7,
    "response": "Non"
  },
  {
    "questionId": 8,
    "response": "Aucune de ces réponses."
  },
  {
    "questionId": 9,
    "response": "Aucune de ces réponses."
  },
  {
    "questionId": 10,
    "response": "Non"
  },
  {
    "questionId": 11,
    "response": "Notre rapport d'empreinte carbone inclut une déclaration claire de notre engagement en faveur de la réduction de notre empreinte carbone."
  },
  {
    "questionId": 12,
    "response": "Nous choisissons en priorité des fournisseurs qui adoptent les meilleures pratiques en matière de durabilité."
  },
  {
    "questionId": 14,
    "response": "Je ne sais pas"
  },
  {
    "questionId": 17,
    "response": "Nous intégrons des critères environnementaux dans nos contrats fournisseurs, afin de les inciter à adopter des pratiques durables."
  },
  {
    "questionId": 22,
    "response": "Nous avons défini des objectifs pour réduire l'empreinte hydrique de notre chaîne d'approvisionnement."
  },
  {
    "questionId": 60,
    "response": "Nous offrons des produits ou des services à prix réduit aux groupes défavorisés."
  },
  {
    "questionId": 61,
    "response": "Oui : veuillez indiquer le nombre d'heures"
  },
  {
    "questionId": 62,
    "response": "Nous mettons en place un programme de jumelage des dons des travailleur·euses où l'entreprise égale les contributions des travailleur·euses aux œuvres de bienfaisance locales, doublant ainsi efficacement l'impact."
  },
  {
    "questionId": 64,
    "response": "Notre conseil d'administration est composé d'au moins un·e membre qui n'est pas un·e fondateur·trice ou un·e propriétaire de l'entreprise."
  },
  {
    "questionId": 63,
    "response": "<1%"
  },
  {
    "questionId": 65,
    "response": "Une expertise environnementale. Par exemple un·e expert·e en développement durable, un·e expert·e scientifique, une organisation territoriale ou sans but lucratif."
  },
  {
    "questionId": 66,
    "response": "Aucune de ces réponses."
  },
  {
    "questionId": 67,
    "response": "Aucune de ces réponses."
  },
  {
    "questionId": 68,
    "response": "1-24%"
  },
  {
    "questionId": 69,
    "response": "Non"
  },
  {
    "questionId": 70,
    "response": "Aucune de ces réponses."
  },
  {
    "questionId": 71,
    "response": "1-24%"
  },
  {
    "questionId": 72,
    "response": "Nous intégrons des critères ESG dans la sélection des fournisseurs."
  },
  {
    "questionId": 73,
    "response": "Nous disposons d'une ou plusieurs certifications de qualité ou d'accréditations de tiers attestant de la qualité de nos produits ou services."
  },
  {
    "questionId": 74,
    "response": "Nous intégrons explicitement les performances sociales et environnementales dans les descriptions de poste des cadres."
  },
  {
    "questionId": 75,
    "response": "Un engagement général en matière de responsabilité sociale ou environnementale (par exemple, préservation de l'environnement)."
  },
  {
    "questionId": 76,
    "response": "Nous sensibilisons nos travailleur·euses aux ODD et les impliquons dans la poursuite de ces objectifs."
  },
  {
    "questionId": 77,
    "response": "Évaluation de la matérialité d'impact : Nous avons analysé les enjeux environnementaux, sociaux et de gouvernance (ESG) les plus importants pour l'entreprise, en termes d'impact sur la société et l'environnement."
  },
  {
    "questionId": 78,
    "response": "Notre empreinte carbone, notre stratégie et nos pratiques pour la réduire."
  },
  {
    "questionId": 79,
    "response": "Notre politique et nos performances en matière de promotion de la santé et du bien-être."
  },
  {
    "questionId": 80,
    "response": "Les résultats financiers (au moins transparents pour les travailleur·euses)."
  },
  {
    "questionId": 81,
    "response": "Élaborer un rapport complet de durabilité qui divulgue de manière transparente les impacts, les performances et les progrès de l'entreprise sur les questions importantes."
  },
  {
    "questionId": 82,
    "response": "Code de conduite interne : déclaration écrite sur les normes de conduite professionnelle attendues de tous·tes les travailleur·euses, y compris l'interdiction de comportements inappropriés tels que la fraude, la corruption, le harcèlement et la discrimination."
  },
  {
    "questionId": 83,
    "response": "Des lignes directrices sur l'acceptation et l'offre de cadeaux, divertissements et hospitalités, conformément aux normes légales et éthiques."
  },
  {
    "questionId": 84,
    "response": "Litige social"
  },
  {
    "questionId": 85,
    "response": "Oui : préciser"
  },
  {
    "questionId": 86,
    "response": "La désignation d'un·e responsable à la protection des données (DPO - Data Protection Officer)."
  },
  {
    "questionId": 87,
    "response": "Nous avons formalisé la politique de protection de la vie privée avec une déclaration claire sur notre engagement à protéger la vie privée et la confidentialité des informations personnelles."
  },
  {
    "questionId": 88,
    "response": "Non"
  },
  {
    "questionId": 89,
    "response": "1-24%"
  },
  {
    "questionId": 90,
    "response": "EMAS ou ISO 14001 - Système de management environnemental"
  }
]

###Submit the form
POST http://localhost:8080/forms/19/submit