version: "3.8"
services:

# MongoDB Service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ouarraddania
      - MONGO_INITDB_ROOT_PASSWORD=NAXV81maQvxDfWB0
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ouarraddania
      - ME_CONFIG_MONGODB_ADMINPASSWORD=NAXV81maQvxDfWB0
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network